create table if not exists farm_info (
  id integer primary key,
  name text not null,
  tagline text not null,
  location text not null,
  description text not null,
  phone text not null,
  email text not null,
  facebook_url text not null default '',
  instagram_url text not null default '',
  tiktok_url text not null default ''
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text not null,
  price text not null,
  unit text not null,
  image text not null,
  availability boolean not null default true,
  in_stock integer not null default 0
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  date date not null,
  time text not null,
  duration text not null,
  description text not null,
  capacity integer not null default 0,
  booked integer not null default 0,
  availability boolean not null default true,
  price text not null,
  image text not null
);

create table if not exists activities (
  id bigint generated by default as identity primary key,
  title text not null,
  days_available text not null,
  schedule text not null,
  duration text not null,
  description text not null,
  availability boolean not null default true,
  price text not null,
  image text not null
);

create table if not exists pick_and_pay_dates (
  id bigint generated by default as identity primary key,
  date date not null,
  day_of_week text not null,
  start_time text not null,
  end_time text not null,
  available_spots integer not null default 0,
  booked integer not null default 0
);

create table if not exists tesda_courses (
  id text primary key,
  title text not null,
  duration text not null,
  focus text not null,
  image text not null,
  availability boolean not null default false
);

create table if not exists blog_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  author text not null,
  date date not null,
  excerpt text not null,
  content text not null,
  image text not null
);

insert into farm_info (id, name, tagline, location, description, phone, email, facebook_url, instagram_url, tiktok_url)
values (
  1,
  'HDN Integrated Farm',
  'Fresh Produce & Community Events',
  'Brgy. Carolina, Naga City',
  'HDN Integrated Farm is committed to sustainable agriculture and bringing fresh produce directly to our community. We offer farm tours, pick & pay experiences, and regular community events.',
  '+63 (phone number)',
  'hdnintegratedfarm.ph@gmail.com',
  'https://facebook.com',
  'https://instagram.com',
  'https://tiktok.com'
)
on conflict (id) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  location = excluded.location,
  description = excluded.description,
  phone = excluded.phone,
  email = excluded.email,
  facebook_url = excluded.facebook_url,
  instagram_url = excluded.instagram_url,
  tiktok_url = excluded.tiktok_url;

insert into products (id, name, category, description, price, unit, image, availability, in_stock) values
  (1, 'Pineapple', 'Fruits', 'Ripe, juicy pineapples grown organically without pesticides.', '150.00', 'per kg', '/products/pineapple.jpeg', true, 45),
  (2, 'Guava', 'Fruits', 'Farm-fresh guavas, packed with vitamin C and natural antioxidants', '120.00', 'per kg', '/products/guava.jpg', true, 30),
  (3, 'Dragon Fruit', 'Fruits', 'Freshly harvested dragon fruit with tiny crunchy seeds', '180.00', 'per kg', '/products/dragon-fruit.jpeg', true, 60),
  (4, 'Avocado', 'Fruits', 'Creamy, nutrient-rich avocados, ideal for savory and sweet dishes', '150.00', 'per kg', '/products/avocado.jpg', true, 25),
  (5, 'Jackfruit', 'Fruits', 'Harvest-fresh jackfruit, with tender golden pods and natural sweetness.', '200.00', 'per kg', '/products/jack-fruit.jpg', true, 40),
  (6, 'Brahman Stud Cattle', 'Livestock', 'High-quality Brahman stud cattle for breeding purposes.', '7000.00', 'per head', '/products/brahman-male.jpg', true, 5),
  (7, 'Angus Female Cattle', 'Livestock', 'High-quality Angus female cattle. Ideal for breeding and meat production.', '5000.00', 'per head', '/products/angus-female.png', true, 7)
on conflict (id) do nothing;

insert into activities (id, title, days_available, schedule, duration, description, availability, price, image) values
  (1, 'Hand Feed Baby Calves', 'Monday to Friday', '9:00 AM to 4:00 PM', '15 minutes', 'A hands-on experience where you can feed and care for our adorable baby calves.', false, '100.00', '/feed-baby-calves.jpg'),
  (2, 'Kalesa Ride', 'Saturday and Sunday', '10:00 AM to 5:00 PM', '30 minutes', 'Enjoy a traditional kalesa ride around our scenic farm, perfect for families and couples.', true, '150.00', '/kalesa-ride.png')
on conflict (id) do nothing;

insert into pick_and_pay_dates (id, date, day_of_week, start_time, end_time, available_spots, booked) values
  (1, '2026-02-16', 'Sunday', '07:00 AM', '12:00 PM', 40, 15),
  (2, '2026-02-23', 'Sunday', '07:00 AM', '12:00 PM', 40, 28),
  (3, '2026-03-02', 'Sunday', '07:00 AM', '12:00 PM', 40, 5),
  (4, '2026-03-09', 'Sunday', '07:00 AM', '12:00 PM', 40, 12)
on conflict (id) do nothing;

insert into tesda_courses (id, title, duration, focus, image, availability) values
  ('intro-agri-crop-production', 'Introduction to Agricultural Crops Production', '3 to 4 months', 'This course includes the knowledge, skills, and attitude that you must have before working in the agricultural crops production sector.', '/tesda-1.jpg', false),
  ('performing-nursery-operations', 'Performing Nursery Operations', '2 to 3 months', 'This course includes the knowledge, skills, and attitude that you must have in order to perform nursery operations and procedures.', '/tesda-2.jpg', false),
  ('planting-crops', 'Planting Crops', '2 to 3 months', 'This course includes the knowledge, skills, and attitude that you must have in order to plant and manage crops effectively.', '/tesda-3.jpg', false),
  ('caring-maintaining-crops', 'Caring and Maintaining Crops', '1 to 2 months', 'This course includes the knowledge, skills, and attitude that you must have in order to perform plant care and maintenance procedures.', '/tesda-4.jpg', false)
on conflict (id) do nothing;

insert into blog_posts (id, title, slug, author, date, excerpt, content, image) values
  (1, 'Benefits of Farming', 'benefits-farming', 'HDN Integrated Farm Team', '2026-01-15', 'Discover why farming is great for your health and the environment.', 'Fresh farming practices...', '/blog/organic.jpg'),
  (2, 'Seasonal Produce Guide', 'seasonal-produce-guide', 'HDN Integrated Farm Team', '2026-01-10', 'Learn what produce is available in each season and how to select the best options.', 'Seasonal produce...', '/blog/seasonal.jpg'),
  (3, 'Farm to Table Recipes', 'farm-to-table-recipes', 'HDN Integrated Farm Team', '2026-01-05', 'Easy recipes using fresh ingredients from our farm.', 'Farm to table recipes...', '/blog/recipes.jpg')
on conflict (id) do nothing;
